# Header
menu:
  电子书: http://it-ebooks.flygon.net/
  布客新知: /ixinzhi
  作品集: /works
  捐赠名单: /donors
  关于我: /about
  RSS: /atom.xml
  "fork me on github": https://github.com/wizardforcel/blog

# Content
excerpt_link: 更多内容
prev: 上一页
next: 下一页
reply: 评论
share: 分享
fancybox: true

# Sidebar
widgets:
- about
- support
- music
- ad
- recent_posts
- archive
- category
- tagcloud
- link
- gate
- account
- script

# Miscellaneous
google_analytics:
duoshuo_shortname: flhexo
rss: /atom.xml
favicon: http://7u2hdm.com1.z0.glb.clouddn.com/favicon.ico
google_site_verification: NCXVSqxqB-os803-VFMtIEd1SUNJVOIjctCfNYUwD0w
baidu_site_verification: Nzwx7HuplM
bing_site_verification: 9E9EA92F7E5327E1FE8A5196D5253664
music: https://img.hacpai.com/file/2018/11/karera_wo_tame_no_koushinnkyoku-95a27a16.mp3